### ISSUE TITLE
Error with roxygenize() checking version on some Linux configurations

### ISSUE THREAD

**Issue by jknowles** [klutometis/roxygen#802]
Unfortunately I cannot provide a REPREX because this bug depends on the build chain for the package. 

After building R and `roxygen` from source using `clang` and `clang++` on Ubuntu (version details below), the following error occurs:

```
> roxygen2::roxygenize()
Error: invalid version specification ‘6.0.1  ’
```

This appears to be related to how the package version number is parsed, which I think is related to differences in the compiler used at build time for the package.

Here is the traceback:

```
> traceback()
6: stop(gettextf("invalid version specification %s", paste(sQuote(unique(x[!ok])), 
       collapse = ", ")), call. = FALSE, domain = NA)
5: .make_numeric_version(x, strict, .standard_regexps()$valid_package_version, 
       "package_version")
4: package_version(prev)
3: update_roxygen_version(base_path)
2: roxygen_setup(base_path)
1: roxygen2::roxygenize()
```

To help with this, here is my session info. Additionally, I built R using `clang` and then set up my 
`Makevars` to look like this: 

```
CC=/usr/bin/clang
CXX=/usr/bin/clang++
CXX11=/usr/bin/clang++-6.0
```

Session info 
```
 setting  value                       
 version  R version 3.5.1 (2018-07-02)
 os       Ubuntu 18.04.1 LTS          
 system   x86_64, linux-gnu           
 ui       X11                         
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/New_York            
 date     2018-10-17                  
```

Packages 

```
 ! package     * version     date       lib source                         
   assertthat    0.2.0       2017-04-11 [1] CRAN (R 3.5.1)                 
   backports     1.1.2       2017-12-13 [1] CRAN (R 3.5.1)                 
   base64enc     0.1-3       2015-07-28 [1] CRAN (R 3.5.1)                 
   callr         3.0.0       2018-08-24 [1] CRAN (R 3.5.1)                 
   cli           1.0.1       2018-09-25 [1] CRAN (R 3.5.1)                 
   commonmark    1.6         2018-09-30 [1] CRAN (R 3.5.1)                 
   crayon        1.3.4       2017-09-16 [1] CRAN (R 3.5.1)                 
   desc          1.2.0       2018-05-01 [1] CRAN (R 3.5.1)                 
   devtools      1.13.6.9000 2018-10-17 [1] Github (r-lib/devtools@80fc2b5)
   digest        0.6.18      2018-10-10 [1] CRAN (R 3.5.1)                 
   fs            1.2.6       2018-08-23 [1] CRAN (R 3.5.1)                 
   glue          1.3.0       2018-07-17 [1] CRAN (R 3.5.1)                 
   magrittr      1.5         2014-11-22 [1] CRAN (R 3.5.1)                 
   memoise       1.1.0       2017-04-21 [1] CRAN (R 3.5.1)                 
   pkgbuild      1.0.2       2018-10-16 [1] CRAN (R 3.5.1)                 
   pkgload       1.0.1       2018-10-11 [1] CRAN (R 3.5.1)                 
   prettyunits   1.0.2       2015-07-13 [1] CRAN (R 3.5.1)                 
   processx      3.2.0       2018-08-16 [1] CRAN (R 3.5.1)                 
   ps            1.2.0       2018-10-16 [1] CRAN (R 3.5.1)                 
   R6            2.3.0       2018-10-04 [1] CRAN (R 3.5.1)                 
   Rcpp          0.12.19     2018-10-01 [1] CRAN (R 3.5.1)                 
   remotes       2.0.0       2018-10-11 [1] CRAN (R 3.5.1)                 
   rlang         0.2.2       2018-08-16 [1] CRAN (R 3.5.1)                 
 V roxygen2      6.1.0.9000  2018-07-27 [1] CRAN (R 3.5.1)                 
   rprojroot     1.3-2       2018-01-03 [1] CRAN (R 3.5.1)                 
   rstudioapi    0.8         2018-10-02 [1] CRAN (R 3.5.1)                 
   sessioninfo   1.1.0       2018-09-25 [1] CRAN (R 3.5.1)                 
   stringi       1.2.4       2018-07-20 [1] CRAN (R 3.5.1)                 
   stringr       1.3.1       2018-05-10 [1] CRAN (R 3.5.1)                 
   testthat      2.0.1       2018-10-13 [1] CRAN (R 3.5.1)                 
   usethis       1.4.0       2018-08-14 [1] CRAN (R 3.5.1)                 
   withr         2.1.2       2018-03-15 [1] CRAN (R 3.5.1)                 
   xml2          1.2.0       2018-01-24 [1] CRAN (R 3.5.1)                 

[1] /usr/local/lib/R/library
```

**Comment by gaborcsardi** [comment]
This is probably desc not removing the trailing whitespace. AFAIR already fixed in GitHub desc.

**Comment by gaborcsardi** [comment]
Btw. the  `V` in front of roxygen2 suggests that your loaded version of roxygen2 is not the same as the on-disk one. You probably updated roxygen2, but did not restart R?

**Comment by jknowles** [comment]
So I should try: 

```
devtools::install_github("kutometis/roxygen")
```

Then restart R and try again? I'll give it a try now.

**Comment by jknowles** [comment]
Update - it still fails with a fresh install of `roxygen` from GH directly: 

```
 package     * version     date       lib source                             
 assertthat    0.2.0       2017-04-11 [1] CRAN (R 3.5.1)                     
 backports     1.1.2       2017-12-13 [1] CRAN (R 3.5.1)                     
 base64enc     0.1-3       2015-07-28 [1] CRAN (R 3.5.1)                     
 callr         3.0.0       2018-08-24 [1] CRAN (R 3.5.1)                     
 cli           1.0.1       2018-09-25 [1] CRAN (R 3.5.1)                     
 commonmark    1.6         2018-09-30 [1] CRAN (R 3.5.1)                     
 crayon        1.3.4       2017-09-16 [1] CRAN (R 3.5.1)                     
 desc          1.2.0       2018-05-01 [1] CRAN (R 3.5.1)                     
 devtools    * 1.13.6.9000 2018-10-17 [1] Github (r-lib/devtools@80fc2b5)    
 digest        0.6.18      2018-10-10 [1] CRAN (R 3.5.1)                     
 fs            1.2.6       2018-08-23 [1] CRAN (R 3.5.1)                     
 glue          1.3.0       2018-07-17 [1] CRAN (R 3.5.1)                     
 magrittr      1.5         2014-11-22 [1] CRAN (R 3.5.1)                     
 memoise       1.1.0       2017-04-21 [1] CRAN (R 3.5.1)                     
 pkgbuild      1.0.2       2018-10-16 [1] CRAN (R 3.5.1)                     
 pkgload       1.0.1       2018-10-11 [1] CRAN (R 3.5.1)                     
 prettyunits   1.0.2       2015-07-13 [1] CRAN (R 3.5.1)                     
 processx      3.2.0       2018-08-16 [1] CRAN (R 3.5.1)                     
 ps            1.2.0       2018-10-16 [1] CRAN (R 3.5.1)                     
 R6            2.3.0       2018-10-04 [1] CRAN (R 3.5.1)                     
 Rcpp          0.12.19     2018-10-01 [1] CRAN (R 3.5.1)                     
 remotes       2.0.0       2018-10-11 [1] CRAN (R 3.5.1)                     
 rlang         0.2.2       2018-08-16 [1] CRAN (R 3.5.1)                     
 roxygen2      6.1.0.9000  2018-10-17 [1] Github (klutometis/roxygen@cc34200)
 rprojroot     1.3-2       2018-01-03 [1] CRAN (R 3.5.1)                     
 rstudioapi    0.8         2018-10-02 [1] CRAN (R 3.5.1)                     
 sessioninfo   1.1.0       2018-09-25 [1] CRAN (R 3.5.1)                     
 stringi       1.2.4       2018-07-20 [1] CRAN (R 3.5.1)                     
 stringr       1.3.1       2018-05-10 [1] CRAN (R 3.5.1)                     
 testthat      2.0.1       2018-10-13 [1] CRAN (R 3.5.1)                     
 usethis     * 1.4.0       2018-08-14 [1] CRAN (R 3.5.1)                     
 withr         2.1.2       2018-03-15 [1] CRAN (R 3.5.1)                     
 xml2          1.2.0       2018-01-24 [1] CRAN (R 3.5.1) 
```

Same error, same traceback.

**Comment by hadley** [comment]
Can you please give me the results of this:

```R
desc::desc_get("RoxygenNote", file = ".")[[1]]
utils::packageVersion("roxygen2")
```

**Comment by gaborcsardi** [comment]
Desc does not parse the RoxygenNote field. Either roxygen2 needs to parse the version and trim space, or we need to add support for this in desc. Even for the latter, roxygen2 needs an update, because desc_get just returns the value unparsed.

**Comment by plantton** [comment]
I think I have the same issue here again:
Error: invalid version specification ‘7.0.’
